### ISSUE TITLE
Delete `Exit` from navbar

### ISSUE THREAD

**Issue by mferrare** [Digital-Law-Lab/docassemble-CLCSA01ServiceDirectory#20]
### Describe the issue

Docassemble allows us to choose to display a login menu or `Exit` as the menu bar depending on setting of `show login`.  But we want to get rid of the exit item altogether.

Currently `Exit` is hidden by setting `exit label: ""` and hiding the mobile menu by futzing with `navbar-toggler` and `navbar-toggler-icon` CSS styles.  We need to do away with `Exit` altogether so users don't click on it by accident.

### What did you expect to happen?

`Exit` disappears.  Click anywhere to the left of `Safe Exit` button and no unexpected behaviour.

### Have you checked that the issue has not already been raised?

- [X] I did not find any similar issues

**Comment by Sirage-t** [comment]
I noticed this, but did not know why it was showing no text. Now I know.

I suggest that we don't fight with DA. It already has a solid implementation for an exit button, and this will give us more flexibility. We just need to modify the place of the button in the nav.

So I recommend the following.

#### first
Use the built-in `exit *` modifiers:
```yaml
  exit label: 'Safe Exit'
  exit url: 'https://www.google.com'
  exit link: exit
```

We can now easily change the destination link and the behaviour.

#### second

We add some JS magic

```js
/*
 * Place the Safe Exit button outside the toggler
 */

// wrap the code in a daPageLoad trigger so that the code is re-executed when the user navigates from screen to screen
$(document).on('daPageLoad', function () {
  // get the exit button - the text inside `contains` should match `exit label`.
  var escapeRef = $('#danavbar-collapse .nav-link:contains(Safe Exit)');
  escapeRef.parents('.nav-item').remove(); // remove the `li` item for the exit button
  escapeRef.removeClass('nav-link');
  escapeRef.attr('id', 'escapeBtn');
  escapeRef.addClass('btn btn-warning btn-da'); // add classes to make it look like a button
  // check if the mobile nave has other items
  if ($('#danavbar-collapse .navbar-nav').children().length == 0) {
    // the menu only has the exit button so remove it
    $('#danavbar-collapse').remove();
    $('#damobile-toggler').remove();
    // align to the far right
    escapeRef.addClass('ms-auto');
  } else {
    escapeRef.css('margin-left', '10px'); // add space between toggle icon and exit button
  }
  // add the button to the nav
  $('.danavcontainer').append(escapeRef);
});
```

Add this to the end of `f2ddd3f2.js` instead of the code I wrote in PR #19.

The advantage of this code is that it is smarter. It only extracts the exist button, styles it, and appends it to the nav container. It then deletes the toggler (the hamburger menu) only and only if it has no other items. If we are using the menu to display some links, it won't be deleted, instead we just add some space between the new exit button and the toggler button.

**Comment by Sirage-t** [comment]
Btw, if you wanted the css approach, you should use `display: none` to hide the element, then you won't have the unexpected behaviour when clicking to the left. You would also need to add the `ms-auto` to the button so that it sits at the right. 

OR just use the more flexible and controllable JS code above

**Comment by mferrare** [comment]
As suggested we are using `exit *` tags and JS-foo to display exit button.
