### ISSUE TITLE
Make the final screen pretty

### ISSUE THREAD

**Issue by bahlahkay** [Digital-Law-Lab/docassemble-CLCSA01ServiceDirectory#6]
* Not be displayed in table as list or in tiles
* Display the logo of each service
* display whether specialist or statewide

**Comment by mferrare** [comment]
Suggest to base final screen on [iRefer app](https://github.com/LLAW3301/docassemble-LLAW33012020S1P02)

**Comment by Sirage-t** [comment]
@bahlahkay what do you mean by "display whether specialist or statewide"? @mferrare would you be able to explain?

**Comment by Sirage-t** [comment]
I am rewriting some internal logic - subsequently I'm going to open separate issues to keep track of the foundational changes made

**Comment by mferrare** [comment]
@Sirage-t `specialist or statewide` would translate to a generic or specific service in this context.  Specificity can depend on the nature of the service *and* on location.  

Eg: a DV service may be available regardless of location or it may only be available in a particular location and it should only be available if the user selects DV from the list of services.

**Comment by Sirage-t** [comment]
@mferrare  Thanks! I just wanted to confirm what was meant be `statewide`.

So, a specific service is one that requires at least one condition to be matched, whereas a generic service does not require any condition to be met (i.e. specifies no constraints)

Services can then be classified into (in order of priority):
1. exactly what the user wants -  matches all answers
2. might be useful - matches some answers
3. fall-back - matches none (comprises generic services that will be displayed when there isn't a better match)
4. not related - matches none (comprises specific services that were eliminated by user answers)

We will call this Service Classification System (SCS).

A more programmatic way of representing this is by implementing a `match strength` system that indicates how many answers match the specified conditions (we maybe could call them filters) for each service. But this needs to be weighted as questions have varying degrees of importance. I.e. a service that matches the selected legal issue takes priority over one that matches the location for example.  

In order to conform to the SCS, we also need to calculate how many conditions were met out of the total condition count (we will call this `match percentage`),  Eg  a service matching two answers out of two specified conditions should take priority over a service that matches two answers out of three conditions. 

Let me know what your thoughts are on this!

Edit: 
- when sorting, match strength takes precedence over match percentage. Eg a service with match strength of 0.7 and a percentage of 50, should appear before a service that has a strength of 0.5 and a percentage of 80. 

- Match percentage is considered when the match strength of two services or more is equal.

- A match percentage of 100 indicates an exact match.

**Comment by mferrare** [comment]
@Sirage-t  I like it.  It's a lot more elegant than a set of loops or loops and if statements.
